
services:
  db:
    container_name: db
    image: postgres:15
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432

  fastapi_app:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - 8000:8000
    command: /python_app/docker/app.sh
    depends_on:
      - db

volumes:
  pgdbdata: